name: Build Docker Images

env:
  REGISTRY: ghcr.io
  TAG: unity-v0.0.1
  HYSDS_CORE_IMAGE_NAME: ${{ github.repository }}/hysds-core
  MOZART_IMAGE_NAME: ${{ github.repository }}/hysds-mozart
  GRQ_IMAGE_NAME: ${{ github.repository }}/hysds-grq2
  VERDI_IMAGE_NAME: ${{ github.repository }}/hysds-verdi
  UI_IMAGE_NAME: ${{ github.repository }}/hysds-ui
  ADES_WPST_API_IMAGE_NAME: ${{ github.repository }}/ades-wpst-api

on: workflow_dispatch

jobs:

  build-ades-wpst-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: unity-sds/ades_wpst
        path: ades_wpst
    - name: Log in to the container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for ADES WPST API Docker image
      id: metaades
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.ADES_WPST_API_IMAGE_NAME }}
    - name: Build and push ADES WPST API Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: docker/
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.ADES_WPST_API_IMAGE_NAME }}:${{ env.TAG }}
        labels: ${{ steps.metaades.outputs.labels }}